
export const INGREDIENT_SUGGESTIONS: string[] = [
  'Almond',
  'Almond flour',
  'Almond milk',
  'Anchovy',
  'Apple',
  'Apple cider vinegar',
  'Apricot',
  'Artichoke',
  'Arugula',
  'Asparagus',
  'Avocado',
  'Bacon',
  'Baking powder',
  'Baking soda',
  'Balsamic vinegar',
  'Banana',
  'Barley',
  'Basil',
  'Bay leaf',
  'Bean sprouts',
  'Beef',
  'Beef broth',
  'Beef mince',
  'Beetroot',
  'Bell pepper',
  'Black beans',
  'Black olives',
  'Black pepper',
  'Blueberries',
  'Bok choy',
  'Bread',
  'Breadcrumbs',
  'Broccoli',
  'Brown rice',
  'Brussels sprouts',
  'Butter',
  'Buttermilk',
  'Cabbage',
  'Carrot',
  'Cashew nuts',
  'Cauliflower',
  'Celery',
  'Cheddar',
  'Cherry tomatoes',
  'Chicken breast',
  'Chicken broth',
  'Chicken thighs',
  'Chickpeas',
  'Chili flakes',
  'Chili pepper',
  'Chives',
  'Cilantro',
  'Cinnamon',
  'Cloves',
  'Cocoa powder',
  'Coconut milk',
  'Coconut oil',
  'Coriander seeds',
  'Corn',
  'Corn flour',
  'Cornstarch',
  'Cottage cheese',
  'Couscous',
  'Cream',
  'Cream cheese',
  'Cucumber',
  'Cumin',
  'Curry powder',
  'Dark chocolate',
  'Dijon mustard',
  'Dill',
  'Dried oregano',
  'Dried thyme',
  'Duck breast',
  'Egg',
  'Egg noodles',
  'Eggplant',
  'Feta cheese',
  'Fish sauce',
  'Flour',
  'Fresh ginger',
  'Garlic',
  'Garlic powder',
  'Ghee',
  'Gouda',
  'Greek yogurt',
  'Green beans',
  'Green lentils',
  'Green olives',
  'Green onion',
  'Ground beef',
  'Ground pork',
  'Ham',
  'Hazelnuts',
  'Heavy cream',
  'Honey',
  'Hot sauce',
  'Iceberg lettuce',
  'Jalapeno',
  'Jasmine rice',
  'Kale',
  'Kidney beans',
  'Kiwi',
  'Lamb',
  'Leek',
  'Lemon',
  'Lemon juice',
  'Lentils',
  'Lettuce',
  'Lime',
  'Lime juice',
  'Maple syrup',
  'Mayonnaise',
  'Milk',
  'Mint',
  'Miso paste',
  'Mozzarella',
  'Mushrooms',
  'Mustard',
  'Nutmeg',
  'Oat milk',
  'Oats',
  'Olive oil',
  'Onion',
  'Orange',
  'Oregano',
  'Oyster mushrooms',
  'Paprika',
  'Parmesan',
  'Parsley',
  'Pasta',
  'Peanut butter',
  'Peanuts',
  'Pear',
  'Peas',
  'Penne',
  'Pine nuts',
  'Pineapple',
  'Pork',
  'Potato',
  'Pumpkin',
  'Pumpkin seeds',
  'Quinoa',
  'Radish',
  'Raisins',
  'Red cabbage',
  'Red lentils',
  'Red onion',
  'Red wine vinegar',
  'Rice',
  'Rice flour',
  'Rice noodles',
  'Rice vinegar',
  'Ricotta',
  'Rosemary',
  'Salmon',
  'Salt',
  'Sausage',
  'Sesame oil',
  'Sesame seeds',
  'Shallot',
  'Shrimp',
  'Smoked paprika',
  'Sour cream',
  'Soy sauce',
  'Spaghetti',
  'Spinach',
  'Spring onion',
  'Strawberries',
  'Sugar',
  'Sunflower oil',
  'Sunflower seeds',
  'Sweet potato',
  'Sweetcorn',
  'Tahini',
  'Teriyaki sauce',
  'Thyme',
  'Tofu',
  'Tomato',
  'Tomato paste',
  'Tomato puree',
  'Tortilla',
  'Tuna',
  'Turmeric',
  'Turkey breast',
  'Vanilla extract',
  'Vegetable broth',
  'Vegetable oil',
  'Walnuts',
  'Water',
  'Watermelon',
  'White beans',
  'White pepper',
  'White rice',
  'White wine vinegar',
  'Whole wheat flour',
  'Yogurt',
  'Zucchini'
];
